#
# This variables needs to be set for every IOC deployment
# They will added to/substituted in st.cmd
#############

# TODO: Add list of supported IOCs, fail if one asks for the unsupported yet. 

ENGINEER: "Oksana x7028"
LOCATION: "XX ID Hutch X"

# epicsEnvSet("EPICS_CA_AUTO_ADDR_LIST", "NO")
EPICS_CA_ADDR_LIST: "10.5.0.255"

##PREFIX: "XF:11IDB-ES{Det:Eig1M}"
PREFIX: "13SIM1"
# PREFIX: "XF:05ID1-ES{Test-Cam:1}"
#DETECTOR_IP: "10.11.1.3"
DETECTOR_IP: "10.5.1.40"
# Some cameras like PointGrey, for example, are indentified by ID, rather then by IP
CAMERA_ID: "17427898"
ioc_name: yourIOCName

# Deploytment_dir is The root of epics binaries tree 
deployment_dir: /opt/epicsTest

##IOC_TYPE: ADEiger
IOC_TYPE: ADSimDetector
# IOC_TYPE: ADProsilica

##NAME: SimTest
USER: softioc
PORT: 6009