---
- name: test for lopping for deploying different IOCs on the target host
  become: true
  hosts: all
  tasks:
    - include_tasks:  deployAD_IOC.yml
      vars:
        ioc_name: "{{ item }}"
        IOC_TYPE: "{{ _IOCs[item].IOC_TYPE }}"
        PREFIX: "{{ _IOCs[item].PREFIX }}"
        PORT: "{{ _IOCs[item].PORT }}"
        ENGINEER: "{{ _IOCs[item].ENGINEER }}"
        LOCATION: "{{ _IOCs[item].LOCATION }}"
        DETECTOR_IP: "{{ _IOCs[item].DETECTOR_IP }}"
        CAMERA_ID: "{{ _IOCs[item].CAMERA_ID }}"
      with_items: 
        - "{{ ioc_names }}"
    