---
- name: test for lopping for deploying different IOCs on the target host
  become: true
  hosts: all
  tasks:
    - include_tasks:  deployAD_IOC.yml
      vars:
        ioc_name: "{{ item.ioc_name }}"
        IOC_TYPE: "{{ item.IOC_TYPE }}"
        PREFIX: "{{ item.PREFIX }}"
        PORT: "{{ item.PORT }}"
        ENGINEER: "{{ item.ENGINEER }}"
        LOCATION: "{{ item.LOCATION }}"
        DETECTOR_IP: "{{ item.DETECTOR_IP }}"
        CAMERA_ID: "{{ item.CAMERA_ID }}"
      with_items: 
        - "{{ ioc_names }}"
    