########################################
# 
# ADProsilica is a role now
#
########################################

      # This check is added on Jakub Wlodek request. To be evaluated if still needed
      - name: check if binary exists
        shell: 'ls "{{ deployment_dir }}"/support/areaDetector/ADProsilica/iocs/prosilicaIOC/bin/linux-x86_64/prosilicaApp'

      # Check it envPath exists and is symbolyc link
      - stat:
          path: "{{root_ioc_dir}}/{{ioc_name}}/envPaths"
        register: st
  
      - fail:
          msg: "envPaths exists and is a link"
        when: generateEnvPaths == "YES" and st.stat.islnk is defined and st.stat.islnk==True

      - name: create envPaths soft link
        file:
            src: "{{ deployment_dir }}/support/areaDetector/ADProsilica/iocs/prosilicaIOC/iocBoot/iocProsilica/envPaths"
            dest: "{{root_ioc_dir}}/{{ioc_name}}/envPaths"
            owner: softioc
            group: controls
            mode: u=r,g=r,o=r
            state: link
        when: generateEnvPaths == "NO"

      - name: create envPaths for binary deployment in a different folder than iot was compiled in
        blockinfile:
            dest: "{{root_ioc_dir}}/{{ioc_name}}/envPaths"
            create: yes
            owner: softioc
            group: controls
            mode: u=r,g=r,o=r
            block: |
              epicsEnvSet("IOC","iocProsilica")
              epicsEnvSet("TOP","{{ deployment_dir }}/support/areaDetector/ADProsilica/iocs/prosilicaIOC")
              epicsEnvSet("ADPROSILICA","{{ deployment_dir }}/support/areaDetector/ADProsilica/iocs/prosilicaIOC/../..")
              epicsEnvSet("SUPPORT","{{ deployment_dir }}/support")
              epicsEnvSet("ASYN","{{ deployment_dir }}/support/asyn")
              epicsEnvSet("AREA_DETECTOR","{{ deployment_dir }}/support/areaDetector")
              epicsEnvSet("ADSUPPORT","{{ deployment_dir }}/support/areaDetector/ADSupport")
              epicsEnvSet("ADCORE","{{ deployment_dir }}/support/areaDetector/ADCore")
              epicsEnvSet("AUTOSAVE","{{ deployment_dir }}/support/autosave")
              epicsEnvSet("BUSY","{{ deployment_dir }}/support/busy")
              epicsEnvSet("CALC","{{ deployment_dir }}/support/calc")
              epicsEnvSet("SNCSEQ","{{ deployment_dir }}/support/seq")
              epicsEnvSet("SSCAN","{{ deployment_dir }}/support/sscan")
              epicsEnvSet("DEVIOCSTATS","{{ deployment_dir }}/support/iocStats")
              epicsEnvSet("EPICS_BASE","{{ deployment_dir }}/epics-base")
        when: generateEnvPaths == "YES"      


      - name: create auto_settings.req soft link
        file:
            src: "{{ deployment_dir }}/support/areaDetector/ADProsilica/iocs/prosilicaIOC/iocBoot/iocProsilica/auto_settings.req"
            dest: "{{root_ioc_dir}}/{{ioc_name}}/auto_settings.req"
            owner: softioc
            group: controls
            mode: u=r,g=r,o=r
            state: link
#        when: IOC_TYPE == 'ADProsilica' 

      - name: copy ADProsilica st.cmd to {{ioc_name}}
        copy:
            src: "{{ deployment_dir }}/support/areaDetector/ADProsilica/iocs/prosilicaIOC/iocBoot/iocProsilica/st.cmd"
            remote_src: yes
            dest: "{{root_ioc_dir}}/{{ioc_name}}/st.cmd"
            owner: softioc
            group: controls
            mode: u=rwx,g=rwx,o=rx   

#        when: IOC_TYPE == 'ADProsilica' 

      - name: enter correct path to ADProsilica executable
        replace:
          path: "{{root_ioc_dir}}/{{ioc_name}}/st.cmd"
          regexp: '#!../..'
          replace: "#!{{ deployment_dir }}/support/areaDetector/ADProsilica/iocs/prosilicaIOC"
#        when: IOC_TYPE == 'ADProsilica' 

      - name: add path to executable
        lineinfile:
          path: "{{root_ioc_dir}}/{{ioc_name}}/st.cmd"
          insertbefore: BOF
          line: "#!{{ deployment_dir }}/support/areaDetector/ADProsilica/iocs/prosilicaIOC/bin/linux-x86_64/prosilicaApp"

      - name: add < envPaths 
        lineinfile:
          path: "{{root_ioc_dir}}/{{ioc_name}}/st.cmd"
          insertafter: "#!{{ deployment_dir }}"
          line: < envPaths

      - name: Enter IP    
        replace:
          path: "{{root_ioc_dir}}/{{ioc_name}}/st.cmd"
          regexp: '^prosilicaConfig\(\"\$\(PORT\)\", [0-9]*,'
#          after: 'epicsEnvSet\(\"EIGERIP\", \"'
#          after: 'prosilicaConfig\(\"\$\(PORT\)\",'
          replace: 'prosilicaConfig("$(PORT)", {{ DETECTOR_IP }}'


