########################################
# 
# Xspress3IOC_4Ch role 
#
########################################

      - name: create envPaths soft link
        file:
            src: "{{ deployment_dir }}/support/xspress3/iocs/xspress3IOC/iocBoot/iocGSECARS-4Channel/envPaths"
            dest: "{{root_ioc_dir}}/{{ioc_name}}/envPaths"
            owner: xspress3
            group: xspress3
            mode: u=r,g=r,o=r
            state: link

      - name: create auto_settings.req soft link
        file:
            src: "{{ deployment_dir }}/support/xspress3/iocs/xspress3IOC/iocBoot/iocGSECARS-4Channel/auto_settings.req"
            dest: "{{root_ioc_dir}}/{{ioc_name}}/auto_settings.req"
            owner: xspress3
            group: xspress3
            mode: u=r,g=r,o=r
            state: link 

      - name: copy st.cmd to {{ioc_name}}
        copy:
            src: "{{ deployment_dir }}/support/xspress3/iocs/xspress3IOC/iocBoot/iocGSECARS-4Channel/st.cmd"
            remote_src: yes
            dest: "{{root_ioc_dir}}/{{ioc_name}}/st.cmd"
            owner: xspress3
            group: xspress3
            mode: u=rwx,g=rwx,o=rx    
      - name: add env EPICS_CA_MAX_ARRAY_BYTES
        lineinfile:
          path: "{{root_ioc_dir}}/{{ioc_name}}/st.cmd"
          insertbefore: BOF
          line: 'epicsEnvSet("EPICS_CA_MAX_ARRAY_BYTES", "30000000")'

      - name: add path to executable to st.cmd file in the ioc folder
        lineinfile: 
          path: "{{root_ioc_dir}}/{{ioc_name}}/st.cmd"
          insertbefore: BOF
          line: "#!{{ deployment_dir }}/support/xspress3/iocs/xspress3IOC/bin/linux-x86_64/xspress3App"
      
      # PointGrey st.cmd has << envPaths already
      
      - name: create AutoSave.cmd soft link
        file:
            src: "{{ deployment_dir }}/support/xspress3/iocs/xspress3IOC/iocBoot/iocGSECARS-4Channel/AutoSave.cmd"
            dest: "{{root_ioc_dir}}/{{ioc_name}}/AutoSave.cmd"
            owner: xspress3
            group: xspress3
            mode: u=r,g=r,o=r
            state: link 
    
      - name: create SCAROI.cmd soft link
        file:
            src: "{{ deployment_dir }}/support/xspress3/iocs/xspress3IOC/iocBoot/iocGSECARS-4Channel/SCAROI.cmd"
            dest: "{{root_ioc_dir}}/{{ioc_name}}/SCAROI.cmd"
            owner: xspress3
            group: xspress3
            mode: u=r,g=r,o=r
            state: link 

      - name: create defaultValueLoad.cmd soft link
        file:
            src: "{{ deployment_dir }}/support/xspress3/iocs/xspress3IOC/iocBoot/iocGSECARS-4Channel/defaultValueLoad.cmd"
            dest: "{{root_ioc_dir}}/{{ioc_name}}/defaultValueLoad.cmd"
            owner: xspress3
            group: xspress3
            mode: u=r,g=r,o=r
            state: link 

      - name: create defaultValuesChan.cmd soft link      
        file:
            src: "{{ deployment_dir }}/support/xspress3/iocs/xspress3IOC/iocBoot/iocGSECARS-4Channel/defaultValuesChan.cmd"
            dest: "{{root_ioc_dir}}/{{ioc_name}}/defaultValuesChan.cmd"
            owner: xspress3
            group: xspress3
            mode: u=r,g=r,o=r
            state: link 
